### ISSUE TITLE
Templates: Login Page

### ISSUE THREAD

**Issue by red-p1xel** [Olena1002/spa4music_composers#12]
Create view template for login user by password

- [ ] create static page
- [ ] install webpack alongside symfony 4.2.2
- [ ] configure webpack
- [ ] install MDL packages
- [ ] init base app.js and require all scripts & stules

**Comment by Olena1002** [comment]
[GUIDE: Material Components Web](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#quick-start-cdn)

**Comment by red-p1xel** [comment]
[nodesource_setup.sh](https://app.gitkraken.com/api/glo/boards/5c979b4a7e701200115b9eaa/attachments/5ca436d7c6c3bd0012696d9a)

**Comment by red-p1xel** [comment]
`DEPRECATED`
