### ISSUE TITLE
Fix errors into entities (Provider, User)

### ISSUE THREAD

**Issue by red-p1xel** [Olena1002/spa4music_composers#3]
### Unneeded relation (field ``user_id``)

https://github.com/Olena1002/spa4music_composers/blob/b46e32eb609381fd0f240ac8916480bbfd4b5e4f/src/Entity/Provider.php#L61-L64

- Remove **field**, **new ArrayCollection() from __constructor()** **getters** and **setters** from entity **Provider**

- Check **User** entity for fix errors

**Comment by Olena1002** [comment]
[Fix](https://github.com/Olena1002/spa4music_composers/pull/6)
